version: "3.3"
services:
  web:
    build: services/frontend
    ports:
      - "5000:5000"
    networks:
      - backend
  reader:
    build: services/reader
    ports:
      - "8081:8081"
    networks:
      - backend
  writer:
    build: services/writer
    ports:
      - "8000:5000"
    networks:
      - backend
  redis:
    image: redis:alpine
    ports:
        - 6379:6379
    volumes:
        - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]

networks:
  backend:
